### PR TITLE
Switch to sdl2_nim bindings

### PR DESCRIPTION
**Pull request by SolitudeSF**
Api is actually more verbose, but big plus is that these bindings are actually documented. Also they follow upstream api changes.

### CODE REVIEW

**Comment by rexim** [comment]
@SolitudeSF did you mark this PR as Work in Progress intentionally? Please let me know when you are ready for the review. Thanks!

**Comment by SolitudeSF** [comment]
yes, just few minor things. want to convert this to proper nimble project.

**Comment by rexim** [comment]
@SolitudeSF sure, take your time.

P.S. I successfully compiled and run the code on my sides. Everything looks good to me. :+1:

**Comment by SolitudeSF** [comment]
i took a liberty to copy the MIT license from https://github.com/tsoding/multik/blob/master/LICENSE and specify your name as `rexim` in nimble file. is this ok?

**Comment by rexim** [comment]
@SolitudeSF Well, if this PR gets merged the code is partially yours. I'm ok with MIT. Are you ok with MIT? If you license your changes under MIT I can super easily merge them with mine, because you basically give me the rights to do so https://github.com/tsoding/multik/blob/6d4e0518003868eb62dc4f4327ab22ba5e66e68e/LICENSE#L8 (`merge` is listed as one of the rights I have)

I usually assume that all of the contributions that are made to @tsoding projects are licensed as the projects themselves (meaning MIT).

**Comment by SolitudeSF** [comment]
with these changes you can also just do `nimble install https://github.com/tsoding/vitanim` to have `vitanim` installed userwide.

**Comment by rexim** [comment]
@SolitudeSF thank you for the contribution :+1:

**Pull request merged**
